- Codigo/Frota/Core/Marcapecainsumo.cs
- Codigo/Frota/Core/Service/IMarcaPecaInsumoService.cs
- Codigo/Frota/FrotaWeb/Controllers/MarcaPecaInsumoController.cs
- Codigo/Frota/FrotaWeb/FrotaWeb.csproj
- Codigo/Frota/FrotaWeb/Mappers/MarcaPecaInsumoProfile.cs
- Codigo/Frota/FrotaWeb/Models/MarcaPecaInsumoViewModel.cs
- Codigo/Frota/FrotaWeb/Program.cs
- Codigo/Frota/FrotaWeb/Views/MarcaPecaInsumo/Create.cshtml
- Codigo/Frota/FrotaWeb/Views/MarcaPecaInsumo/Delete.cshtml
- Codigo/Frota/FrotaWeb/Views/MarcaPecaInsumo/Details.cshtml
- Codigo/Frota/FrotaWeb/Views/MarcaPecaInsumo/Edit.cshtml
- Codigo/Frota/FrotaWeb/Views/MarcaPecaInsumo/Index.cshtml
- Codigo/Frota/FrotaWeb/Views/Shared/_Layout.cshtml
- Codigo/Frota/Service/MarcaPecaInsumoService.cs
Realizar a review, por gentileza. #11
> Finalização da implementação inicial da task #11

- Codigo/Frota/Core/Core.csproj
- Codigo/Frota/Core/DTO/FrotaDTO.cs
- Codigo/Frota/Core/DTO/ModeloVeiculoDTO.cs
- Codigo/Frota/Core/DTO/UnidadeAdministrativaDTO.cs
- Codigo/Frota/Core/Service/IFrotaService.cs
- Codigo/Frota/Core/Service/IModeloVeiculoService.cs
- Codigo/Frota/Core/Service/IUnidadeAdministrativaService.cs
- Codigo/Frota/FrotaWeb/Controllers/ModeloVeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/FrotaWeb/Mappers/FrotaProfile.cs
- Codigo/Frota/FrotaWeb/Mappers/ModeloVeiculoProfile.cs
- Codigo/Frota/FrotaWeb/Mappers/UnidadeAdministrativaProfile.cs
- Codigo/Frota/FrotaWeb/Models/VeiculoViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Veiculo/Create.cshtml
- Codigo/Frota/FrotaWeb/wwwroot/css/form.css
- Codigo/Frota/FrotaWeb/wwwroot/css/site.css
- Codigo/Frota/Service/FrotaService.cs
- Codigo/Frota/Service/ModeloVeiculoService.cs
- Codigo/Frota/Service/UnidadeAdministrativaService.cs
Correções na controller de modeloVeiculo.
Campos do formulário mantidos  pensando na alteração do design.
https://github.com/user-attachments/assets/64ed3100-4881-48e4-8c73-ee88cd3ba43c
> Melhorias no cadastro de veículos.

- Codigo/Frota/Core/Service/IAbastecimentoService.cs
- Codigo/Frota/Service/AbastecimentoService.cs
- Codigo/Frota/Service/VeiculoService.cs
- Codigo/Frota/ServiceTests/AbastecimentoServiceTests.cs
- Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
- Correções na service do abastecimento
> Implementação do teste de integração da service de abastacimento

- Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
- Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
- Codigo/Frota/FrotaWeb/Controllers/FornecedorController.cs
- Codigo/Frota/FrotaWeb/Controllers/FrotaController.cs
- Codigo/Frota/FrotaWeb/Controllers/ManutencaoController.cs
- Codigo/Frota/FrotaWeb/Controllers/ManutencaoPecaInsumoController.cs
- Codigo/Frota/FrotaWeb/Controllers/MarcaPecaInsumoController.cs
- Codigo/Frota/FrotaWeb/Controllers/MarcaVeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/ModeloVeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/PecaInsumoController.cs
- Codigo/Frota/FrotaWeb/Controllers/PercursoController.cs
- Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
- Codigo/Frota/FrotaWeb/Controllers/SolicitacaoManutencaoController.cs
- Codigo/Frota/FrotaWeb/Controllers/UnidadeAdministrativaController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoPecaInsumoController.cs
- Codigo/Frota/FrotaWeb/Controllers/VistoriaController.cs
Um pequeno aprimoramento necessário foi feito na parte do login também.
> Autorização de acordo com os papéis implementada.

- AnaliseProjeto/dump-frota-dados.sql
- AnaliseProjeto/readme.txt
Foi criado um dump de dados para testes com alguns dados para inserções no banco, além disso um readme.txt contendo uma pessoa de cada papel.
> Criação do dump de dados 

- Codigo/Frota/Core/Service/IPessoaService.cs
- Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
- Codigo/Frota/FrotaWeb/Models/PessoaViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Pessoa/Index.cshtml
- Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
- Codigo/Frota/Service/PessoaService.cs
Foi melhorada a implementação da paginação na service, agora ela também possibilita a filtragem a partir de alguma string.
Implementada a filtragem por busca.
Adicionado um texto informativo para exibir a quantidade de resultados.
> Melhoria e implementação da index de pessoas/condutores, close #174

- Codigo/Frota/FrotaWebTests/Controllers/AbastecimentoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/FornecedorControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/FrotaControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/PessoaControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/VeiculoControllerTests.cs
- Codigo/Frota/Service/FrotaService.cs
- Codigo/Frota/Service/PessoaService.cs
- Codigo/Frota/Service/VeiculoService.cs
- Codigo/Frota/ServiceTests/FrotaServiceTests.cs
- Codigo/Frota/ServiceTests/PessoaServiceTests.cs
- Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
> Ajustes nos testes de unidade e integração

- Codigo/Frota/Core/Service/IAbastecimentoService.cs
- Codigo/Frota/Core/Service/IFornecedorService.cs
- Codigo/Frota/Core/Service/IFrotaService.cs
- Codigo/Frota/Core/Service/IPessoaService.cs
- Codigo/Frota/Core/Service/IVeiculoService.cs
- Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
- Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
- Codigo/Frota/FrotaWeb/Controllers/FornecedorController.cs
- Codigo/Frota/FrotaWeb/Controllers/FrotaController.cs
- Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoPecaInsumoController.cs
- Codigo/Frota/FrotaWeb/Models/FornecedorViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Abastecimento/Index.cshtml
- Codigo/Frota/FrotaWeb/Views/Fornecedor/Create.cshtml
- Codigo/Frota/FrotaWeb/Views/Fornecedor/Delete.cshtml
- Codigo/Frota/FrotaWeb/Views/Fornecedor/Details.cshtml
- Codigo/Frota/FrotaWeb/Views/Fornecedor/Edit.cshtml
- Codigo/Frota/Service/AbastecimentoService.cs
- Codigo/Frota/Service/FornecedorService.cs
- Codigo/Frota/Service/FrotaService.cs
- Codigo/Frota/Service/PessoaService.cs
- Codigo/Frota/Service/VeiculoService.cs
Implementado o vinculo de fornecedor a frota, adicionar campo ativo ao fornecedor, além disso também foi feito um ajuste nas controladoras para tratamento de erro na listagem de registros de acordo respectivos a cada frota, o que justifica uma quantidade maior do que o esperado para registros modificados.
> Implementação dos ajustes para o manter fornecedor

- Codigo/Frota/FrotaWeb/Controllers/FornecedorController.cs
- Codigo/Frota/Service/FornecedorService.cs
- Codigo/Frota/Service/Service.csproj
Mover método da controladora de ConsultarCnpj para classe serviço de fornecedor, além de ajustar alguns doc comments dos métodos da classe de serviço.
> Refatoração na controladora de fornecedor

- .github/pull_request_template.md
Futuras prs agora contarão com um template para uma descrição mais formal e padronizada.
> Template para prs adicionado

- Codigo/Frota/Core/Service/IMarcaVeiculoService.cs
- Codigo/Frota/FrotaWeb/Controllers/MarcaVeiculoController.cs
- Codigo/Frota/FrotaWeb/Models/MarcaVeiculoViewModel.cs
- Codigo/Frota/Service/MarcaVeiculoService.cs
</div>
Foi solicitado que o cadastro das marcas de veículos tivessem vinculo com a frota.
Basta acessar a rota web e realizar as operações de CRUD para as marcas de veículos.
**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**
> Implementados os ajustes na marca veículo, close #189

- Codigo/Frota/Core/Service/IModeloVeiculoService.cs
- Codigo/Frota/Core/Service/IUnidadeAdministrativaService.cs
- Codigo/Frota/Core/Service/IVeiculoService.cs
- Codigo/Frota/FrotaWeb/Controllers/ModeloVeiculoController.cs
- Codigo/Frota/FrotaWeb/Controllers/UnidadeAdministrativaController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/Service/ModeloVeiculoService.cs
- Codigo/Frota/Service/UnidadeAdministrativaService.cs
- Codigo/Frota/Service/VeiculoService.cs
</div>
Associar os modelos de veículos a frota do usuário logado.
Basta ir em home/ModeloVeiculo/
Sem prints
> Associação de modelos de veículos com a frota

- Codigo/Frota/FrotaWeb/Models/PecaInsumoViewModel.cs
</div>
Campos adicionados em peça/insumo:
mesesGarantia e kmGarantia com valores padrão de acordo com o banco.  
Não houve.
Ir em create da controladora peçaInsumo.
> Campos adicionados em peça/insumo

- Codigo/Frota/Core/Core.csproj
- Codigo/Frota/Core/DTO/VeiculoDTO.cs
- Codigo/Frota/Core/Pecainsumo.cs
- Codigo/Frota/Core/Service/IPessoaService.cs
- Codigo/Frota/Core/Service/IVeiculoService.cs
- Codigo/Frota/Core/Service/ServiceException.cs
- Codigo/Frota/Core/Unidadeadministrativa.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/Service/AbastecimentoService.cs
- Codigo/Frota/Service/FrotaService.cs
- Codigo/Frota/Service/PessoaService.cs
- Codigo/Frota/Service/VeiculoService.cs
- Codigo/Frota/ServiceTests/AbastecimentoServiceTests.cs
- Codigo/Frota/ServiceTests/FornecedorServiceTests.cs
- Codigo/Frota/ServiceTests/FrotaServiceTests.cs
- Codigo/Frota/ServiceTests/ManutencaoPecaInsumoServiceTests.cs
- Codigo/Frota/ServiceTests/ManutencaoServiceTests.cs
- Codigo/Frota/ServiceTests/MarcaPecaInsumoServiceTests.cs
- Codigo/Frota/ServiceTests/MarcaVeiculoServiceTests.cs
- Codigo/Frota/ServiceTests/ModeloVeiculoServiceTests.cs
- Codigo/Frota/ServiceTests/PecaInsumoServiceTests.cs
- Codigo/Frota/ServiceTests/PercursoServiceTests.cs
- Codigo/Frota/ServiceTests/PessoaServiceTests.cs
- Codigo/Frota/ServiceTests/ServiceTests.csproj
- Codigo/Frota/ServiceTests/SolicitacaoManutencaoServiceTests.cs
- Codigo/Frota/ServiceTests/UnidadeAdministrativaServiceTests.cs
- Codigo/Frota/ServiceTests/VeiculoPecaInsumoServiceTests.cs
- Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
</div>
Corrigir erros de compilação nos testes de integração.
Compilar o projeto ServiceTests e rodar os testes.
> Corrigir erros de compilação nos testes de integração

- Codigo/Frota/FrotaWeb/FrotaWeb.csproj
</div>
Implementar a tag <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel> no arquivo .csproj do projeto para configurar o modelo de hospedagem do aplicativo ASP.NET Core.
[Explique as alterações realizadas neste Pull Request de forma detalhada. Use o checklist markdown como o exemplo abaixo]
Nenhuma mudança extra foi realizada além do que estava planejado.
Executando normalmente o projeto. A mudança é percebida no momento de hospedar a aplicação, analisando o funcionamento do servidor.
> Ajuste necessário para hospedagem correta do site

- Codigo/Frota/Core/Core.csproj
- Codigo/Frota/Core/Service/IFornecedorService.cs
- Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
- Codigo/Frota/FrotaWebTests/Controllers/AbastecimentoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/FornecedorControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/FrotaControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/ManutencaoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/MarcaPecaInsumoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/MarcaVeiculoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/ModeloVeiculoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/PecaInsumoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/PercursoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/PessoaControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/SolicitacaoManutencaoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/UnidadeAdministrativaControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/VeiculoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/VeiculoPecaInsumoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/VistoriaControllerTests.cs
- Codigo/Frota/ServiceTests/FornecedorServiceTests.cs
- Codigo/Frota/ServiceTests/ManutencaoServiceTests.cs
- Codigo/Frota/ServiceTests/ServiceTests.csproj
- Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
</div>
Corrigir erros de compilação nos testes de unidade.
Compilar o projeto FrotaWebTests e rodar os testes.
> Corrigir erros de compilação nos testes de unidade

- Codigo/Frota/FrotaWeb/Views/Shared/_Layout.cshtml
- Codigo/Frota/FrotaWeb/wwwroot/css/site.css
</div>
Logar no sistema e deslogar em seguida.
> Melhoria no modal de deslogar com bootstrap, #233.

- Codigo/Frota/Core/Service/IManutencaoService.cs
- Codigo/Frota/Core/Service/ServiceException.cs
- Codigo/Frota/FrotaWeb/Controllers/ManutencaoController.cs
- Codigo/Frota/FrotaWeb/Models/ManutencaoViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Manutencao/Create.cshtml
- Codigo/Frota/FrotaWeb/Views/Manutencao/Delete.cshtml
- Codigo/Frota/Service/ManutencaoService.cs
…anutenção, #232.
</div>
Realizar teste exploratório para o CSU - Manter Manutenção
Tente excluir uma manutenção que está relacionado a uma manutençãoPecaInsumo
> Realizar teste exploratório para o CSU - Manter Manutenção

- Codigo/Frota/FrotaWeb/Filter/CustomExceptionFilter.cs
- Codigo/Frota/FrotaWeb/Program.cs
- Codigo/Frota/FrotaWeb/Views/Shared/Error.cshtml
</div>
Adicionar filtro para tratar exceções que não foram tratadas
Encontre alguma exceção para ver o sistema redirecionando para a página de erro.
Como o sistema tá top e não lança exceção atoa adicione logo throw new Execption(); na homeController para ver a mágica =D
> Adicionado filtro para tratar exceções que não foram tratadas

- Codigo/Frota/Core/Service/IVistoriaService.cs
- Codigo/Frota/FrotaWeb/Controllers/VistoriaController.cs
- Codigo/Frota/Service/VistoriaService.cs
</div>
Realizar teste exploratório para o CSU - Manter Vistoria
Vá até vistoria/index.
> Realizado teste exploratório para o CSU - Manter Vistoria

- Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
- Codigo/Frota/FrotaWeb/Models/PessoaViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Pessoa/Create.cshtml
- Codigo/Frota/FrotaWeb/Views/Pessoa/Index.cshtml
- Codigo/Frota/Service/PessoaService.cs
</div>
A realização do teste exploratório de manter pessoa e garantir que todas as ações esperadas fossem realizadas com sucesso.
Executando todas as operações de CRUD normalmente
**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**
> Teste exploratório de manter pessoa

- Codigo/Frota/Core/Service/IAbastecimentoService.cs
- Codigo/Frota/Core/Service/IPessoaService.cs
- Codigo/Frota/Core/Service/ServiceException.cs
- Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
- Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
- Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
- Codigo/Frota/FrotaWeb/Models/AbastecimentoViewModel.cs
- Codigo/Frota/FrotaWeb/Views/Abastecimento/Create.cshtml
- Codigo/Frota/FrotaWeb/Views/Abastecimento/Delete.cshtml
- Codigo/Frota/FrotaWeb/Views/Abastecimento/Edit.cshtml
- Codigo/Frota/FrotaWeb/Views/Abastecimento/Index.cshtml
- Codigo/Frota/FrotaWebTests/Controllers/AbastecimentoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/ManutencaoControllerTests.cs
- Codigo/Frota/FrotaWebTests/Controllers/VistoriaControllerTests.cs
- Codigo/Frota/Service/AbastecimentoService.cs
- Codigo/Frota/Service/PessoaService.cs
- Codigo/Frota/ServiceTests/AbastecimentoServiceTests.cs
- Codigo/Frota/ServiceTests/ManutencaoServiceTests.cs
- Codigo/Frota/ServiceTests/PessoaServiceTests.cs
- Codigo/Frota/ServiceTests/VistoriaServiceTests.cs
</div>
Realizar teste exploratório para o CSU - Manter Abastecimento
> Realizado teste exploratório para o CSU - Manter Abastecimento

- Codigo/Frota/FrotaWeb/Controllers/ManutencaoController.cs
- Codigo/Frota/FrotaWeb/Controllers/SolicitacaoManutencaoController.cs
- Codigo/Frota/FrotaWeb/Views/Manutencao/Index.cshtml
- Codigo/Frota/FrotaWeb/Views/SolicitacaoManutencao/Index.cshtml
- Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
…citação, close #261
</div>
Implementada a filtragem das manutenções e solicitações de manutenções por veículo, permitindo uma visualização simplificada contendo apenas os registros de determinado veículo.
Basta acessar as listagens de ambos os cadastros e filtrar de acordo com os veículos já cadastrados.
**Certifique-se de revisar o código e testar as alterações localmente antes de solicitar/fazer o merge.**
> Feat: Implementada a filtragem de manutenções e solicitações de acordo com o veículo
